AlignParameters:
  Enabled: false
ClassLength:
  CountComments: false
  Max: 200
Documentation:
  Enabled: false
LineLength:
  Max: 120
MethodLength:
  CountComments: false
  Max: 15
  Exclude:
    - 'spec/**/*'
Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'spec/**/*'
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'app/graphql/**/*.rb'

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'app/admin/dashboard.rb'
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'Gemfile'
    - 'Guardfile'
    - 'Capfile'
    - 'Rakefile'
    - 'vendor/**/*'

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
  SupportedStyles:
    - aligned
    - indented
Style/StringLiterals:
  EnforcedStyle: double_quotes
Layout/DotPosition:
  EnforcedStyle: leading
  Enabled: truez
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Lambda:
  Enabled: false
Lint/UnusedBlockArgument:
  Enabled: false
